### ISSUE TITLE
isn't it unreachable code?

### ISSUE THREAD

**Issue by qsona** [twada/array-foreach#1]
Hi, I have a question.
https://github.com/twada/array-foreach/blob/ec89b4f8f54ea1458838c2f0256accf0d865b6cc/index.js#L19
I think it is unreachable to here because `ary.forEach` throws TypeError if ary is undefined or null. So this check is unnecessary, isn't it?
I'm sorry I don't know anything about older browser's behaviors so I would appreciate if you could tell me about it. Thanks.

**Comment by twada** [comment]
@qsona Oh you're absolutely right! Shame on me... I'll fix it ASAP.

**Comment by qsona** [comment]
Thank you for quick response!

**Comment by twada** [comment]
@qsona  Just released [1.0.1](https://github.com/twada/array-foreach/releases/tag/v1.0.1). Thank you so much!
